# [character]
# use_symbol_for_status = true
# symbol = "âœ"
# style_success = "bold #00A652"
# style_failure = "bold #df382c"

[package]
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[hostname]
ssh_only = false
format =  "@[$hostname](white bold) "
trim_at = ".companyname.com"
disabled = false

[directory]
truncation_length = 25
truncate_to_repo = false
format = "[$path]($style)[$lock_symbol]($lock_style) "
style = "white"
#prefix = " ğŸ“‚ï¸ "

#format = "$all"
